In [2]:
import numpy as np
import pandas as pd
!pip install xgboost
!pip install tensorflow
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

import tensorflow as tf

Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in d:\ana\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in d:\ana\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 1.0 MB/s eta 0:01:41
   ---------------------------------------- 0.5/101.7 MB 1.0 MB/s eta 0:01:41
   ---------------------------------------- 0.8/101.7 MB 1.0 MB/s eta 0:01:41
   ---------------------------------------- 1.0/101.7 MB 982.4 kB/s eta 0:01:43
    --------------------------------------- 1.3/101.7 MB 974.3 kB/s eta 0:01:44
    --------------------------------------- 1.6/101.7 MB 979.4 kB/s eta 0:01:43
    --------------------------------------- 1.6/101.7 MB 979.4 kB/s eta 0:01:43
    --------------------------------------- 1.8/101.7 MB 981.9 kB/s eta 0:01:42
    --------------------------------------- 2.1/101.7 MB 989.9 kB/s eta 0:01:41
    --------------------------------------- 2.4/101.7 MB 963.9 kB/s eta 0:01:44
    --------------------------------------- 2.4/101.7 MB 963.9 kB/s eta 0:01:44
   - -------------------------------------- 2.6/101.7 MB 969.1 kB/s eta 0:01:43
   - -------------------------------------- 2.9/101.7 MB 966.2 kB/s eta 0:01:43
   - -------------------------------------- 3.1/101.7 MB 968.7 kB/s eta 0:01:42
   - -------------------------------------- 3.4/101.7 MB 970.2 kB/s eta 0:01:42
   - -------------------------------------- 3.4/101.7 MB 970.2 kB/s eta 0:01:42
   - -------------------------------------- 3.7/101.7 MB 972.5 kB/s eta 0:01:41
   - -------------------------------------- 3.9/101.7 MB 966.5 kB/s eta 0:01:42
   - -------------------------------------- 4.2/101.7 MB 968.9 kB/s eta 0:01:41
   - -------------------------------------- 4.2/101.7 MB 968.9 kB/s eta 0:01:41
   - -------------------------------------- 4.5/101.7 MB 967.6 kB/s eta 0:01:41
   - -------------------------------------- 4.7/101.7 MB 968.4 kB/s eta 0:01:41
   - -------------------------------------- 5.0/101.7 MB 970.5 kB/s eta 0:01:40
   -- ------------------------------------- 5.2/101.7 MB 972.4 kB/s eta 0:01:40
   -- ------------------------------------- 5.2/101.7 MB 972.4 kB/s eta 0:01:40
   -- ------------------------------------- 5.5/101.7 MB 973.7 kB/s eta 0:01:39
   -- ------------------------------------- 5.8/101.7 MB 973.1 kB/s eta 0:01:39
   -- ------------------------------------- 6.0/101.7 MB 974.0 kB/s eta 0:01:39
   -- ------------------------------------- 6.0/101.7 MB 974.0 kB/s eta 0:01:39
   -- ------------------------------------- 6.3/101.7 MB 970.5 kB/s eta 0:01:39
   -- ------------------------------------- 6.6/101.7 MB 971.3 kB/s eta 0:01:38
   -- ------------------------------------- 6.8/101.7 MB 972.6 kB/s eta 0:01:38
   -- ------------------------------------- 7.1/101.7 MB 973.0 kB/s eta 0:01:38
   -- ------------------------------------- 7.1/101.7 MB 973.0 kB/s eta 0:01:38
   -- ------------------------------------- 7.3/101.7 MB 974.3 kB/s eta 0:01:37
   -- ------------------------------------- 7.6/101.7 MB 974.8 kB/s eta 0:01:37
   --- ------------------------------------ 7.9/101.7 MB 974.8 kB/s eta 0:01:37
   --- ------------------------------------ 8.1/101.7 MB 972.2 kB/s eta 0:01:37
   --- ------------------------------------ 8.1/101.7 MB 972.2 kB/s eta 0:01:37
   --- ------------------------------------ 8.4/101.7 MB 973.3 kB/s eta 0:01:36
   --- ------------------------------------ 8.7/101.7 MB 972.3 kB/s eta 0:01:36
   --- ------------------------------------ 8.9/101.7 MB 973.4 kB/s eta 0:01:36
   --- ------------------------------------ 9.2/101.7 MB 973.9 kB/s eta 0:01:35
   --- ------------------------------------ 9.2/101.7 MB 973.9 kB/s eta 0:01:35
   --- ------------------------------------ 9.4/101.7 MB 974.8 kB/s eta 0:01:35
   --- ------------------------------------ 9.7/101.7 MB 975.5 kB/s eta 0:01:35
   --- ----------------------------------- 10.0/101.7 MB 976.1 kB/s eta 0:01:34
   --- ----------------------------------- 10.2/101.7 MB 975.6 kB/s eta 0:01:34
   --- ----------------------------------- 10.2/101.7 MB 975.6 kB/s eta 0:01:34
   ---- ---------------------------------- 10.5/101.7 MB 975.2 kB/s eta 0:01:34
   ---- ---------------------------------- 10.7/101.7 MB 974.7 kB/s eta 0:01:34
   ---- ---------------------------------- 11.0/101.7 MB 974.6 kB/s eta 0:01:34
   ---- ---------------------------------- 11.0/101.7 MB 974.6 kB/s eta 0:01:34
   ---- ---------------------------------- 11.3/101.7 MB 975.2 kB/s eta 0:01:33
   ---- ---------------------------------- 11.5/101.7 MB 975.6 kB/s eta 0:01:33
   ---- ---------------------------------- 11.8/101.7 MB 975.8 kB/s eta 0:01:33
   ---- ---------------------------------- 12.1/101.7 MB 976.3 kB/s eta 0:01:32
   ---- ---------------------------------- 12.1/101.7 MB 976.3 kB/s eta 0:01:32
   ---- ---------------------------------- 12.3/101.7 MB 975.9 kB/s eta 0:01:32
   ---- ---------------------------------- 12.6/101.7 MB 974.9 kB/s eta 0:01:32
   ---- ---------------------------------- 12.8/101.7 MB 975.2 kB/s eta 0:01:32
   ---- ---------------------------------- 12.8/101.7 MB 975.2 kB/s eta 0:01:32
   ----- --------------------------------- 13.1/101.7 MB 975.9 kB/s eta 0:01:31
   ----- --------------------------------- 13.4/101.7 MB 976.6 kB/s eta 0:01:31
   ----- --------------------------------- 13.6/101.7 MB 976.6 kB/s eta 0:01:31
   ----- --------------------------------- 13.6/101.7 MB 976.6 kB/s eta 0:01:31
   ----- --------------------------------- 13.9/101.7 MB 975.4 kB/s eta 0:01:31
   ----- --------------------------------- 14.2/101.7 MB 975.2 kB/s eta 0:01:30
   ----- --------------------------------- 14.4/101.7 MB 975.8 kB/s eta 0:01:30
   ----- --------------------------------- 14.4/101.7 MB 975.8 kB/s eta 0:01:30
   ----- --------------------------------- 14.7/101.7 MB 971.6 kB/s eta 0:01:30
   ----- --------------------------------- 14.9/101.7 MB 971.6 kB/s eta 0:01:30
   ----- --------------------------------- 15.2/101.7 MB 971.7 kB/s eta 0:01:29
   ----- --------------------------------- 15.2/101.7 MB 971.7 kB/s eta 0:01:29
   ----- --------------------------------- 15.5/101.7 MB 971.2 kB/s eta 0:01:29
   ------ -------------------------------- 15.7/101.7 MB 971.5 kB/s eta 0:01:29
   ------ -------------------------------- 16.0/101.7 MB 971.1 kB/s eta 0:01:29
   ------ -------------------------------- 16.3/101.7 MB 970.8 kB/s eta 0:01:29
   ------ -------------------------------- 16.3/101.7 MB 970.8 kB/s eta 0:01:29
   ------ -------------------------------- 16.5/101.7 MB 970.5 kB/s eta 0:01:28
   ------ -------------------------------- 16.8/101.7 MB 971.1 kB/s eta 0:01:28
   ------ -------------------------------- 17.0/101.7 MB 971.4 kB/s eta 0:01:28
   ------ -------------------------------- 17.0/101.7 MB 971.4 kB/s eta 0:01:28
   ------ -------------------------------- 17.3/101.7 MB 971.5 kB/s eta 0:01:27
   ------ -------------------------------- 17.6/101.7 MB 970.8 kB/s eta 0:01:27
   ------ -------------------------------- 17.8/101.7 MB 971.5 kB/s eta 0:01:27
   ------ -------------------------------- 18.1/101.7 MB 971.5 kB/s eta 0:01:27
   ------ -------------------------------- 18.1/101.7 MB 971.5 kB/s eta 0:01:27
   ------- ------------------------------- 18.4/101.7 MB 971.1 kB/s eta 0:01:26
   ------- ------------------------------- 18.6/101.7 MB 970.5 kB/s eta 0:01:26
   ------- ------------------------------- 18.9/101.7 MB 971.5 kB/s eta 0:01:26
   ------- ------------------------------- 19.1/101.7 MB 971.6 kB/s eta 0:01:25
   ------- ------------------------------- 19.1/101.7 MB 971.6 kB/s eta 0:01:25
   ------- ------------------------------- 19.4/101.7 MB 971.9 kB/s eta 0:01:25
   ------- ------------------------------- 19.7/101.7 MB 971.7 kB/s eta 0:01:25
   ------- ------------------------------- 19.9/101.7 MB 972.2 kB/s eta 0:01:25
   ------- ------------------------------- 19.9/101.7 MB 972.2 kB/s eta 0:01:25
   ------- ------------------------------- 20.2/101.7 MB 972.4 kB/s eta 0:01:24
   ------- ------------------------------- 20.4/101.7 MB 972.4 kB/s eta 0:01:24
   ------- ------------------------------- 20.7/101.7 MB 971.5 kB/s eta 0:01:24
   ------- ------------------------------- 20.7/101.7 MB 971.5 kB/s eta 0:01:24
   -------- ------------------------------ 21.0/101.7 MB 971.9 kB/s eta 0:01:24
   -------- ------------------------------ 21.2/101.7 MB 972.2 kB/s eta 0:01:23
   -------- ------------------------------ 21.5/101.7 MB 972.5 kB/s eta 0:01:23
   -------- ------------------------------ 21.8/101.7 MB 972.4 kB/s eta 0:01:23
   -------- ------------------------------ 21.8/101.7 MB 972.4 kB/s eta 0:01:23
   -------- ------------------------------ 22.0/101.7 MB 972.6 kB/s eta 0:01:22
   -------- ------------------------------ 22.3/101.7 MB 972.5 kB/s eta 0:01:22
   -------- ------------------------------ 22.5/101.7 MB 972.8 kB/s eta 0:01:22
   -------- ------------------------------ 22.5/101.7 MB 972.8 kB/s eta 0:01:22
   -------- ------------------------------ 22.8/101.7 MB 972.8 kB/s eta 0:01:22
   -------- ------------------------------ 23.1/101.7 MB 972.5 kB/s eta 0:01:21
   -------- ------------------------------ 23.3/101.7 MB 972.7 kB/s eta 0:01:21
   --------- ----------------------------- 23.6/101.7 MB 972.9 kB/s eta 0:01:21
   --------- ----------------------------- 23.6/101.7 MB 972.9 kB/s eta 0:01:21
   --------- ----------------------------- 23.9/101.7 MB 972.5 kB/s eta 0:01:21
   --------- ----------------------------- 24.1/101.7 MB 972.7 kB/s eta 0:01:20
   --------- ----------------------------- 24.4/101.7 MB 972.9 kB/s eta 0:01:20
   --------- ----------------------------- 24.4/101.7 MB 972.9 kB/s eta 0:01:20
   --------- ----------------------------- 24.6/101.7 MB 972.6 kB/s eta 0:01:20
   --------- ----------------------------- 24.9/101.7 MB 973.0 kB/s eta 0:01:19
   --------- ----------------------------- 25.2/101.7 MB 973.3 kB/s eta 0:01:19
   --------- ----------------------------- 25.4/101.7 MB 973.5 kB/s eta 0:01:19
   --------- ----------------------------- 25.4/101.7 MB 973.5 kB/s eta 0:01:19
   --------- ----------------------------- 25.7/101.7 MB 973.7 kB/s eta 0:01:19
   --------- ----------------------------- 26.0/101.7 MB 973.8 kB/s eta 0:01:18
   ---------- ---------------------------- 26.2/101.7 MB 973.6 kB/s eta 0:01:18
   ---------- ---------------------------- 26.5/101.7 MB 973.7 kB/s eta 0:01:18
   ---------- ---------------------------- 26.5/101.7 MB 973.7 kB/s eta 0:01:18
   ---------- ---------------------------- 26.7/101.7 MB 974.0 kB/s eta 0:01:17
   ---------- ---------------------------- 27.0/101.7 MB 973.6 kB/s eta 0:01:17
   ---------- ---------------------------- 27.3/101.7 MB 973.8 kB/s eta 0:01:17
   ---------- ---------------------------- 27.5/101.7 MB 973.9 kB/s eta 0:01:17
   ---------- ---------------------------- 27.5/101.7 MB 973.9 kB/s eta 0:01:17
   ---------- ---------------------------- 27.8/101.7 MB 974.2 kB/s eta 0:01:16
   ---------- ---------------------------- 28.0/101.7 MB 974.1 kB/s eta 0:01:16
   ---------- ---------------------------- 28.3/101.7 MB 974.2 kB/s eta 0:01:16
   ---------- ---------------------------- 28.3/101.7 MB 974.2 kB/s eta 0:01:16
   ---------- ---------------------------- 28.6/101.7 MB 973.8 kB/s eta 0:01:16
   ----------- --------------------------- 28.8/101.7 MB 973.9 kB/s eta 0:01:15
   ----------- --------------------------- 29.1/101.7 MB 973.8 kB/s eta 0:01:15
   ----------- --------------------------- 29.4/101.7 MB 973.8 kB/s eta 0:01:15
   ----------- --------------------------- 29.4/101.7 MB 973.8 kB/s eta 0:01:15
   ----------- --------------------------- 29.6/101.7 MB 973.6 kB/s eta 0:01:15
   ----------- --------------------------- 29.9/101.7 MB 973.4 kB/s eta 0:01:14
   ----------- --------------------------- 30.1/101.7 MB 973.9 kB/s eta 0:01:14
   ----------- --------------------------- 30.1/101.7 MB 973.9 kB/s eta 0:01:14
   ----------- --------------------------- 30.4/101.7 MB 972.6 kB/s eta 0:01:14
   ----------- --------------------------- 30.7/101.7 MB 972.4 kB/s eta 0:01:14
   ----------- --------------------------- 30.9/101.7 MB 972.2 kB/s eta 0:01:13
   ----------- --------------------------- 30.9/101.7 MB 972.2 kB/s eta 0:01:13
   ----------- --------------------------- 31.2/101.7 MB 971.7 kB/s eta 0:01:13
   ------------ -------------------------- 31.5/101.7 MB 973.6 kB/s eta 0:01:13
   ------------ -------------------------- 31.7/101.7 MB 973.4 kB/s eta 0:01:12
   ------------ -------------------------- 31.7/101.7 MB 973.4 kB/s eta 0:01:12
   ------------ -------------------------- 32.0/101.7 MB 973.4 kB/s eta 0:01:12
   ------------ -------------------------- 32.2/101.7 MB 973.6 kB/s eta 0:01:12
   ------------ -------------------------- 32.5/101.7 MB 973.5 kB/s eta 0:01:12
   ------------ -------------------------- 32.8/101.7 MB 973.3 kB/s eta 0:01:11
   ------------ -------------------------- 32.8/101.7 MB 973.3 kB/s eta 0:01:11
   ------------ -------------------------- 33.0/101.7 MB 974.3 kB/s eta 0:01:11
   ------------ -------------------------- 33.3/101.7 MB 974.0 kB/s eta 0:01:11
   ------------ -------------------------- 33.6/101.7 MB 974.6 kB/s eta 0:01:10
   ------------ -------------------------- 33.8/101.7 MB 974.3 kB/s eta 0:01:10
   ------------ -------------------------- 33.8/101.7 MB 974.3 kB/s eta 0:01:10
   ------------- ------------------------- 34.1/101.7 MB 973.8 kB/s eta 0:01:10
   ------------- ------------------------- 34.3/101.7 MB 973.5 kB/s eta 0:01:10
   ------------- ------------------------- 34.6/101.7 MB 973.6 kB/s eta 0:01:09
   ------------- ------------------------- 34.9/101.7 MB 973.8 kB/s eta 0:01:09
   ------------- ------------------------- 34.9/101.7 MB 973.8 kB/s eta 0:01:09
   ------------- ------------------------- 35.1/101.7 MB 973.7 kB/s eta 0:01:09
   ------------- ------------------------- 35.4/101.7 MB 974.5 kB/s eta 0:01:09
   ------------- ------------------------- 35.7/101.7 MB 974.4 kB/s eta 0:01:08
   ------------- ------------------------- 35.7/101.7 MB 974.4 kB/s eta 0:01:08
   ------------- ------------------------- 35.9/101.7 MB 974.3 kB/s eta 0:01:08
   ------------- ------------------------- 36.2/101.7 MB 974.0 kB/s eta 0:01:08
   ------------- ------------------------- 36.4/101.7 MB 973.9 kB/s eta 0:01:07
   -------------- ------------------------ 36.7/101.7 MB 974.0 kB/s eta 0:01:07
   -------------- ------------------------ 36.7/101.7 MB 974.0 kB/s eta 0:01:07
   -------------- ------------------------ 37.0/101.7 MB 974.0 kB/s eta 0:01:07
   -------------- ------------------------ 37.2/101.7 MB 974.7 kB/s eta 0:01:07
   -------------- ------------------------ 37.5/101.7 MB 974.0 kB/s eta 0:01:06
   -------------- ------------------------ 37.5/101.7 MB 974.0 kB/s eta 0:01:06
   -------------- ------------------------ 37.7/101.7 MB 974.5 kB/s eta 0:01:06
   -------------- ------------------------ 38.0/101.7 MB 974.0 kB/s eta 0:01:06
   -------------- ------------------------ 38.3/101.7 MB 974.0 kB/s eta 0:01:06
   -------------- ------------------------ 38.3/101.7 MB 974.0 kB/s eta 0:01:06
   -------------- ------------------------ 38.5/101.7 MB 973.8 kB/s eta 0:01:05
   -------------- ------------------------ 38.8/101.7 MB 973.7 kB/s eta 0:01:05
   -------------- ------------------------ 39.1/101.7 MB 973.8 kB/s eta 0:01:05
   --------------- ----------------------- 39.3/101.7 MB 973.6 kB/s eta 0:01:05
   --------------- ----------------------- 39.3/101.7 MB 973.6 kB/s eta 0:01:05
   --------------- ----------------------- 39.6/101.7 MB 973.7 kB/s eta 0:01:04
   --------------- ----------------------- 39.8/101.7 MB 974.3 kB/s eta 0:01:04
   --------------- ----------------------- 40.1/101.7 MB 974.5 kB/s eta 0:01:04
   --------------- ----------------------- 40.1/101.7 MB 974.5 kB/s eta 0:01:04
   --------------- ----------------------- 40.4/101.7 MB 973.9 kB/s eta 0:01:03
   --------------- ----------------------- 40.6/101.7 MB 974.0 kB/s eta 0:01:03
   --------------- ----------------------- 40.9/101.7 MB 974.3 kB/s eta 0:01:03
   --------------- ----------------------- 41.2/101.7 MB 973.8 kB/s eta 0:01:03
   --------------- ----------------------- 41.2/101.7 MB 973.8 kB/s eta 0:01:03
   --------------- ----------------------- 41.4/101.7 MB 974.1 kB/s eta 0:01:02
   --------------- ----------------------- 41.7/101.7 MB 974.3 kB/s eta 0:01:02
   ---------------- ---------------------- 41.9/101.7 MB 974.4 kB/s eta 0:01:02
   ---------------- ---------------------- 42.2/101.7 MB 974.2 kB/s eta 0:01:02
   ---------------- ---------------------- 42.2/101.7 MB 974.2 kB/s eta 0:01:02
   ---------------- ---------------------- 42.5/101.7 MB 974.0 kB/s eta 0:01:01
   ---------------- ---------------------- 42.7/101.7 MB 973.7 kB/s eta 0:01:01
   ---------------- ---------------------- 43.0/101.7 MB 974.5 kB/s eta 0:01:01
   ---------------- ---------------------- 43.3/101.7 MB 974.8 kB/s eta 0:01:00
   ---------------- ---------------------- 43.3/101.7 MB 974.8 kB/s eta 0:01:00
   ---------------- ---------------------- 43.5/101.7 MB 974.6 kB/s eta 0:01:00
   ---------------- ---------------------- 43.8/101.7 MB 976.5 kB/s eta 0:01:00
   ---------------- ---------------------- 44.0/101.7 MB 975.9 kB/s eta 0:01:00
   ---------------- ---------------------- 44.0/101.7 MB 975.9 kB/s eta 0:01:00
   ---------------- ---------------------- 44.3/101.7 MB 976.0 kB/s eta 0:00:59
   ----------------- --------------------- 44.6/101.7 MB 976.4 kB/s eta 0:00:59
   ----------------- --------------------- 44.8/101.7 MB 976.4 kB/s eta 0:00:59
   ----------------- --------------------- 44.8/101.7 MB 976.4 kB/s eta 0:00:59
   ----------------- --------------------- 45.1/101.7 MB 976.9 kB/s eta 0:00:58
   ----------------- --------------------- 45.4/101.7 MB 977.2 kB/s eta 0:00:58
   ----------------- --------------------- 45.6/101.7 MB 976.9 kB/s eta 0:00:58
   ----------------- --------------------- 45.6/101.7 MB 976.9 kB/s eta 0:00:58
   ----------------- --------------------- 45.9/101.7 MB 976.4 kB/s eta 0:00:58
   ----------------- --------------------- 46.1/101.7 MB 977.2 kB/s eta 0:00:57
   ----------------- --------------------- 46.4/101.7 MB 976.9 kB/s eta 0:00:57
   ----------------- --------------------- 46.7/101.7 MB 977.5 kB/s eta 0:00:57
   ----------------- --------------------- 46.7/101.7 MB 977.5 kB/s eta 0:00:57
   ----------------- --------------------- 46.9/101.7 MB 974.0 kB/s eta 0:00:57
   ----------------- --------------------- 46.9/101.7 MB 974.0 kB/s eta 0:00:57
   ------------------ -------------------- 47.2/101.7 MB 969.3 kB/s eta 0:00:57
   ------------------ -------------------- 47.2/101.7 MB 969.3 kB/s eta 0:00:57
   ------------------ -------------------- 47.4/101.7 MB 966.6 kB/s eta 0:00:57
   ------------------ -------------------- 47.4/101.7 MB 966.6 kB/s eta 0:00:57
   ------------------ -------------------- 47.7/101.7 MB 963.2 kB/s eta 0:00:57
   ------------------ -------------------- 48.0/101.7 MB 960.7 kB/s eta 0:00:56
   ------------------ -------------------- 48.0/101.7 MB 960.7 kB/s eta 0:00:56
   ------------------ -------------------- 48.2/101.7 MB 959.9 kB/s eta 0:00:56
   ------------------ -------------------- 48.5/101.7 MB 958.7 kB/s eta 0:00:56
   ------------------ -------------------- 48.8/101.7 MB 958.3 kB/s eta 0:00:56
   ------------------ -------------------- 48.8/101.7 MB 958.3 kB/s eta 0:00:56
   ------------------ -------------------- 49.0/101.7 MB 958.5 kB/s eta 0:00:55
   ------------------ -------------------- 49.3/101.7 MB 959.4 kB/s eta 0:00:55

ModuleNotFoundError: No module named 'tensorflow'

In [3]:
import xgboost as xgb

In [4]:
pd.read_csv('snote.csv')

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,1162,85,0,159,0,0,13567,56581,21,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,3093,85,1283,317,2,2,13568,4023,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,1603,85,1266,175,9,2,13571,4,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,4275,85,1124,318,2,2,13567,3442,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,4333,85,1194,318,2,2,13570,3567,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386741,794,28,65407,111,53,17,3744,15125,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386742,731,28,54705,111,53,17,644,15225,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386743,50,28,49164,19,443,6,2160,4796722,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386744,712,28,51691,111,53,17,571,12714,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386745,671,28,49218,111,443,6,1296,96419,3,3,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5

In [5]:
df = pd.read_csv('snote.csv')

In [6]:

# Extract features (all columns except the target variable)
X = df.drop(columns=['Label'])

# Extract target variable (label)
y = df['Label']

In [7]:
# Binarize the target variable for class 0 vs. all others
y_binary = (y == 0).astype(int)

In [ ]:
from sklearn.model_selection import train_test_split

# Split the dataset into training (70%) and test (30%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Further split the training set into training (70%) and validation (30%) sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=42)

# Now have to X_train, X_val, X_test for features and y_train, y_val, y_test for labels

In [ ]:
#2 Gradient boosting machine algorithm

xgb_classifier = xgb.XGBClassifier(random_state=42)


xgb_classifier.fit(X_train, y_train)

# y_pred = xgb_classifier.predict(X_test)

In [ ]:
# Make predictions 
y_pred_gbm = xgb_classifier.predict(X_test)

In [ ]:
# Compute confusion matrix for each classifier

from sklearn.metrics import confusion_matrix

cm_gbm = confusion_matrix(y_test, y_pred_gbm)

print(cm_gbm)

In [ ]:
# Compute TPR, TNR, FPR, FNR for each classifier using confusion matrix
def compute_metrics(cm):
    TP = cm[1, 1]
    TN = cm[0, 0]
    FP = cm[0, 1]
    FN = cm[1, 0]

    tpr = TP / (TP + FN)
    tnr = TN / (TN + FP)
    fpr = FP / (FP + TN)
    fnr = FN / (FN + TP)

    return tpr, tnr, fpr, fnr

# Compute metrics for each classifier
tpr_gbm, tnr_gbm, fpr_gbm, fnr_gbm = compute_metrics(cm_gbm)

print(compute_metrics(cm_gbm))

In [ ]:
from sklearn.metrics import accuracy_score

# Compute accuracy for each classifier

accuracy_gbm = accuracy_score(y_test, y_pred_gbm)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision_gbm = precision_score(y_test, y_pred_gbm, average='weighted')
recall_gbm = recall_score(y_test, y_pred_gbm, average='weighted')
f1_gbm = f1_score(y_test, y_pred_gbm, average='weighted')

In [ ]:
# Print computed metrics for each classifier


print("Gradient Boosting Machines Metrics:")
print("Precision:", precision_gbm)
print("Recall:", recall_gbm)
print("F1 Score:", f1_gbm)
print()

In [ ]:
from sklearn.preprocessing import LabelBinarizer

In [ ]:
!pip install dice-ml

In [ ]:
import dice_ml
from dice_ml.utils import helpers # helper functions

In [ ]:

continuous_features = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

print("Continuous feature names:", continuous_features)

In [ ]:
continuous_features =  ['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min']
outcome_name = 'Label'

In [23]:
# Increase the display width for pandas DataFrames
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)  # Don't wrap DataFrame in output

In [24]:
# Step 1: Initialize DiCE
d = dice_ml.Data(dataframe=df, continuous_features= continuous_features, outcome_name=outcome_name)

# Using sklearn backend
m = dice_ml.Model(model= xgb_classifier, backend="sklearn")
# Using method=random for generating CFs
exp = dice_ml.Dice(d, m, method="random")


e1 = exp.generate_counterfactuals(X_train[1:21], total_CFs=1, desired_class= 0)
e1.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 20/20 [08:14<00:00, 24.73s/it]

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std   Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std    Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean   Bwd IAT Std   Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      714      58     49251      62       443         6       3514         317454             7            10            591.0      6425.833496            517.0              0.0         84.428574       192.729401           1412.0              0.0        642.583313       648.618652  22103.582031    53.551174   19840.882812  53176.289062  206394.296875      1.150408  307504.8125  51250.804688  87612.296875  216161.171875    98.109619  317380.71875  35264.523438  70112.078125  210710.71875     1.150408              0              0              0              0             164             224   22.050484    31.50069          0.0       1412.0    389.824066   566.357361    320760.75             0             1             0             0             0             0               0             0            1.0    412.754913         84.428574        642.583313               0               0                 0               0               0                 0                 7               591                10              6425                 -1                261                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -           2214.2               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3537     193         9     131       103         1        991             50             0             2              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0      94173.0          170.0           0.0       64475.0       28909.0          1.0           1.0          0.0          0.0          0.0         20.0       26136.0          0.0         23.0         50.0              0              0              0              0               0               6         0.0     91327.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 1                 0                  0                 33                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max    Idle Min Label
0       -      -        -      -        -        -         -    25056436.0            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -  58954135.4     -

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      347      28     51188      68      1900        17        979        6968891            23             1           2971.0            133.0            133.0            123.0         129.17392         4.174078            133.0            133.0             133.0              0.0    445.40802     3.443877      302995.25     767516.25     2984362.0           0.0    6968886.0  316767.53125  782663.6875    2984362.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0             184               8    3.300382    0.143495        123.0        133.0    129.479996     4.134408    17.093334             0             0             0             0             0             0               0             0            0.0       134.875         129.17392             133.0               0               0                 0               0               0                 0                23              2971                 1               133                 -1                 -1                 23                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -          3046.8               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               1.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      443       0     54208       6        53        17      17466        6999573             3             1             84.0             28.0             28.0             28.0              28.0              0.0             28.0             28.0              28.0              0.0    16.000975     0.571463     2333191.25     1527778.5    4000023.25   999415.3125    6000158.5    3000079.25  1414134.625   4000023.25    2000135.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.428598    0.142866         28.0         28.0          28.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          35.0              28.0              28.0               0               0                 0               0               0                 0                 3                84                 1                28                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -          12633.0                -               1.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      238       0     50014       6        53        17        960        7998257             3             1            105.0             35.0             35.0             35.0              35.0              0.0             35.0             35.0              35.0              0.0    17.503813     0.500109     2666085.75   1155172.125     3999963.0     1998171.0    6000086.0     3000043.0  1414100.375    3999963.0    2000123.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.375082    0.125027         35.0         35.0          35.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         43.75              35.0              35.0               0               0                 0               0               0                 0                 3               105                 1                35                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               1.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      540       0     56037       6        53        17      11923        7952813             3             1        98.135544        32.711849        32.711849        32.711849         32.711849              0.0        32.711849        32.711849         32.711849              0.0    16.452944     0.502967      2650938.0     1141014.0    3968438.75   1984681.625    5953120.5    2976560.25  1402728.125   3968438.75  1984681.625          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.377225    0.125742    32.711849    32.711849     32.711849          0.0          0.0             0             0             0             0             0             0               0             0            0.0     40.889809         32.711849         32.711849               0               0                 0               0               0                 0                 3                98                 1                32                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -            1.0                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1390      85       173     175        10         2        252          23766             3             1            567.0            166.0            156.0             58.0            3951.0              1.0            178.0             68.0            4580.0              0.0      99340.0      63808.0        30160.0       21912.0        8504.0       12763.0       6569.0       15646.0      14850.0      13828.0          2.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     64565.0     59203.0         51.0        160.0        7457.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0        6150.0            3258.0            3673.0               0               0                 0               0               0                 0                 3               566                 0               165                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -       208.1            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -          13750.0                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1624      50     57048     195        53        17       4979          16272             0             2              0.0            132.0              0.0              0.0               0.0              0.0            104.0             28.0              66.0        53.740116  8112.094238   122.910522        16272.0           0.0       16272.0       16272.0          0.0           0.0          0.0          0.0          0.0      16272.0       16272.0          0.0      16272.0      16272.0              0              0              0              0               0              16         0.0  122.910522         28.0        104.0     53.333332     43.87862  1925.333374             0             0             0             0             0             0               0             0            0.0          80.0               0.0              66.0               0               0                 0               0               0                 0                 0                 0                 2               132                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -       209039.0          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               1.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      650       0     58410       6        53        17       5297        7984529             3             1             84.0             28.0             28.0             28.0              28.0              0.0             28.0             28.0              28.0              0.0    14.027126     0.500969     2661509.75    1145610.75     3984347.0     2000017.0    5984512.0     2992256.0    1403028.5    3984347.0    2000165.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.375727    0.125242         28.0         28.0          28.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          35.0              28.0              28.0               0               0                 0               0               0                 0                 3                84                 1                28                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -   8661.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std   Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std    Fwd IAT Max  Fwd IAT Min    Bwd IAT Tot  Bwd IAT Mean   Bwd IAT Std   Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std   Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      566      58     49291      48       443         6       4026         323794             6             9            591.0      5671.902344            517.0              0.0              98.5        207.14801           1412.0              0.0        630.211365       671.562439  19341.529297    46.325756   23128.166016  56841.757812  207553.453125      1.554298     311085.0       62217.0  96203.484375  219859.484375    25.599571  116240.882812  14530.110352  26094.134766  77190.664062     1.554298              0              0              0              0             132             204   18.530302   27.795454          0.0       1412.0    391.431396   577.704712  333748.28125             0             1             0             0             0             0               0             0            1.0    417.526825              98.5        630.211365               0               0                 0               0               0                 0                 6               591                 9              5671                 -1                261                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -          1.0            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot   Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot   Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std    Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1497      58     51638     173       443        17       1523        3065009            19            24      2643.974854     11258.510742           1250.0             33.0        134.533737       276.889679           1250.0             22.0        470.049744       524.595764  4535.993652    14.258175    71937.21875  366139.84375     2381924.5      0.656644   3032148.75  162610.953125  549259.8125   2385487.25    16.523771   3065009.25  133518.421875     501472.0   2404527.25     0.656644              0              0              0              0             157             192     6.42109    7.837085         22.0       1250.0    339.717133   474.394562  225102.421875             0             0             0             0             0             0               0             0            1.0    347.529724        134.533737        470.049744               0               0                 0               0               0                 0                19              2643                24             11258                 -1                 -1                 19                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -              1.0                -                -                -                -               1.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3500      85       157     318         2         2       7702          68372             2             1             38.0             17.0             15.0             16.0             200.0              1.0             18.0             18.0              39.0              0.0      18091.0      13729.0        81000.0       55955.0       48492.0       18013.0      38679.0       60614.0          0.0      47226.0       8400.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               2               1     13844.0     21284.0         18.0         15.0         144.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         181.0             198.0              38.0               0               0                 0               0               0                 0                 2                37                 0                17                  0                  0                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -       534.5           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -           7496.0                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2194      85       153     317         2         2       3398           6175             0             2              0.0             40.0              1.0              1.0               1.0              1.0             35.0              8.0              49.0              9.0      77258.0      84774.0        12165.0           0.0       14435.0        2507.0          1.0           1.0          0.0          0.0          0.0       5916.0        7257.0          0.0       6022.0       6162.0              0              0              0              0               0               2         0.0     84461.0          8.0         33.0         150.0        304.0        316.0             0             0             0             0             0             0               0             0            0.0         239.0               0.0              48.0               0               0                 0               0               0                 0                 0                 0                 1                40                  0                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -      25904413.8               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -  35575877.2           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1181      85       454     161        12         2      29515          19455             3             1             34.0              5.0              3.0              4.0             108.0              1.0              6.0              4.0              19.0              0.0      48687.0      68143.0        25664.0       15955.0        1179.0           1.0        675.0       11292.0      10500.0       9570.0          1.0          0.0           1.0          0.0          0.0          0.0              1              0              0              1               4               1     68943.0     63732.0          4.0          3.0          39.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          39.0             106.0              18.0               0               0                 0               0               0                 0                 3                33                 0                 5                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std    Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -  33836290.0        -     -

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3089      85      1279     317         2         2      29287          80245             3             1             79.0             21.0             19.0             20.0             223.0              1.0             22.0             22.0              47.0              0.0      30936.0      19128.0        74925.0       78834.0       52288.0        9908.0      54470.0       56920.0      52801.0      50652.0       4654.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     19833.0      9308.0         22.0         19.0         176.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         193.0             219.0              46.0               0               0                 0               0               0                 0                 3                78                 0                21                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -       7833.0               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -           1.0             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0    13124      96     56170     430        53        17       3036          13840             0             2              0.0             84.0              0.0              0.0               0.0              0.0             50.0             34.0              42.0        11.313708  6069.364258   144.508667        13840.0           0.0       13840.0       13840.0          0.0           0.0          0.0          0.0          0.0      13840.0       13840.0          0.0      13840.0      13840.0              0              0              0              0               0              16         0.0  144.508667         34.0         50.0     39.333332     9.237604    85.333336             0             0             0             0             0             0               0             0            0.0          59.0               0.0              42.0               0               0                 0               0               0                 0                 0                 0                 2                84                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -       914.3            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1147       0     52528       7        53        17      12157        6950390             2             1             76.0             38.0             38.0             38.0              38.0              0.0             38.0             38.0              38.0              0.0    16.401957      0.43163      3475195.0   697979.4375     3968741.0     2981649.0    3968741.0     3968741.0          0.0    3968741.0    3968741.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              16               8    0.287754    0.143877         38.0         38.0          38.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0     50.666668              38.0              38.0               0               0                 0               0               0                 0                 2                76                 1                38                 -1                 -1                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1611      50     55539     195        53        17       5540          13284             0             2              0.0            159.0              0.0              0.0               0.0              0.0            116.0             43.0              79.5        51.618793  11969.286133   150.557068        13284.0           0.0       13284.0       13284.0          0.0           0.0          0.0          0.0          0.0      13284.0       13284.0          0.0      13284.0      13284.0              0              0              0              0               0              16         0.0  150.557068         43.0        116.0     67.333336    42.146568  1776.333374             0             0             0             0             0             0               0             0            0.0         101.0               0.0              79.5               0               0                 0               0               0                 0                 0                 0                 2               159                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  8622.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               0.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean   Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std   Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1397      50     49220     194       443         6        907        3037000             8            10            591.0           6876.0            517.0              0.0            73.875       180.912323           1412.0              0.0        687.599976       632.827698   2458.67627     5.926901    178647.0625      653805.0     2708019.0           1.0    3024428.0  432061.15625  1006749.125    2708019.0        384.0     328069.0  36452.109375  70788.382812     215129.0          1.0              0              0              0              0             172             224    2.634178    3.292723          0.0       1412.0         393.0   561.268921  315022.78125             0             1             0             0             0             0               0             0            1.0    414.833344            73.875        687.599976               0               0                 0               0               0                 0                 8               591                10              6876                 -1                261                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -   14727.0             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -               1.0                 -                 -                -           -          -          -          -         -        -        -        -   0.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2133      85        18     317         7         1      24670          64193             1             1              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0       4656.0        92532.0           0.0       63761.0       28360.0          1.0           1.0          0.0          0.0          0.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               3               3      2373.0     25459.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 0                 0                  0                 37                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 0)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min  Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -  18539.0      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -  -14073657.1            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

In [23]:
e2 = exp.generate_counterfactuals(X_test[500:521], total_CFs=1, desired_class= 1)
e2.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 21/21 [02:52<00:00,  8.23s/it]

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len     Fwd Pkts/s     Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      398      28     63505      68      3702        17       2337              9             1             1            656.0            656.0            656.0            656.0             656.0              0.0            656.0            656.0             656.0              0.0  145777776.0  222222.21875            9.0           0.0           9.0           9.0          0.0           0.0          0.0          0.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0               8               8  111111.109375  111111.109375        656.0        656.0         656.0          0.0          0.0             0             0             0             0             0             0               0             0            1.0         984.0             656.0             656.0               0               0                 0               0               0                 0                 1               656                 1               656                 -1                 -1                  1                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -  241.0  30369.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     4653      85      1570     318         2         2      15745          67619             2             1             39.0             18.0             16.0             17.0             209.0              1.0             19.0             19.0              40.0              0.0      20603.0      14478.0        80251.0       53159.0       46916.0       18026.0      37564.0       59512.0          0.0      45677.0       7298.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               2               1     14593.0     22038.0         19.0         16.0         152.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         191.0             206.0              39.0               0               0                 0               0               0                 0                 2                38                 0                18                  0                  0                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max  Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   45.0  30156.0      -        -        -         -             -       5224.0            -               -               -           969.5               -           3669.7               -           711.2               -           2957.8               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -  86796517.7           -             -             -             -             -              -              -          -          -       594.5           -       1827.3           -           -          1.0            -            -            -            -            -              -          1.0             -            -           2743.6                -              -              -                -              -            1.0              1.0                -                -           7039.0                -              -1.0           42389.0                 -                -   5755798.9          -          -  16730072.7         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     4479      85      1361     318         2         2      28404          71698             2             1             36.0             16.0             14.0             15.0             189.0              1.0             17.0             17.0              38.0              0.0      14531.0      10520.0        84213.0       57762.0       51999.0       19291.0      41151.0       63008.0          0.0      50366.0      10796.0          0.0           1.0          0.0          0.0          0.0              1              0              0              1               2               1     10631.0     17958.0         17.0         14.0         134.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         157.0             187.0              37.0               0               0                 0               0               0                 0                 2                35                 0                16                  0                  0                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   65.0  10764.0      -        -        -         -             -            -            -               -               -               -               -           3171.9          3204.9               -          1105.8           4009.2               -           -           -             -            -            -            -           -            -  63904666.3           -           -           -   10652945.0           -           -           -             -             -             -             -              -       177751.0          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -       5615.6                -                -              -              -                -              -            1.0                -            838.0         140260.0                -        6895044.0              -1.0                 -             606.0              1.0           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1164       0     52906       7        53        17      14708        7003538             2             1             94.0             47.0             47.0             47.0              47.0              0.0             47.0             47.0              47.0              0.0    20.132681     0.428355      3501769.0   708735.9375     4002921.0     3000617.0    4002921.0     4002921.0          0.0    4002921.0    4002921.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              16               8     0.28557    0.142785         47.0         47.0          47.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0     62.666668              47.0              47.0               0               0                 0               0               0                 0                 2                94                 1                47                 -1                 -1                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max  Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  138.0        -      -        -        -         -             -            -            -        102682.3               -               -               -                -               -               -               -                -               -           -    600633.6             -            -            -            -           -            -           -           -           -  53116232.0            -  54671415.9           -           -             -             -             -             -       221307.0              -          -          -           -       840.8            -           -           -            -            -            -            -            -            -            1.0            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -             423.0              1.0           -          -          -  18856961.9         -        -        -        -   1.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1564     118       443      86     49213         6       2120            508             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0   3935.41748     508.221375           0.0    508.221375    508.221375          0.0           0.0          0.0          0.0          0.0   508.221375    508.221375          0.0   508.221375   508.221375              0              0              0              0               0              40         0.0  3935.41748          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                253                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -           1999.6               -           -           -    91206755.9            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0    12741      96     49170     429       443         6       6348        4812594             1             1              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0     0.415576      4812594.0           0.0     4812594.0     4812594.0          0.0           0.0          0.0          0.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              20              20    0.207788    0.207788          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 1                 0                 -1                259                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std  Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std     Idle Max Idle Min Label
0       -   18.0        -  164.0  26046.0        -    2045.0             -            -      12815.0         48359.3               -               -               -                -               -          1239.3           432.5                -          3460.8  190195705.1           -             -            -            -            -           -   83160437.2  13701538.6           -           -           -            -           -  95580924.5           -             -             -           1.0             -       244993.0              -          -          -       833.3           -            -      3017.4           -          2.0            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -  9636613.0         -        -  117475125.2        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2235      85       207     317         7         1       1255          45374            11            16            381.0            517.0            161.0              1.0             953.0           1165.0            229.0              0.0            1049.0           4812.0      64734.0      48098.0        45993.0       44800.0       37102.0       12763.0      24559.0       39464.0      42589.0      39112.0        240.0      22650.0        9528.0      10392.0      21055.0          2.0              0              0              0              0              46              76     40837.0     51718.0          0.0        215.0        1745.0       2863.0       3080.0             0             1             0             0             0             0               0             0            1.0        1433.0             827.0             886.0               0               0                 0               0               0                 0                11               380                15               516                  0                 44                  6                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  1297.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -  66648921.4             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -          1.0            -            -            -              -            -             -            -                -                -              -              -                -            1.0              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3643       0       443     184     50029         6      16726            104             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0  19230.769531          104.0           0.0         104.0         104.0          0.0           0.0          0.0          0.0          0.0        104.0         104.0          0.0        104.0        104.0              0              0              0              0               0              40         0.0  19230.769531          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                260                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -     6211355.0            -      15362.0               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -   860265.5          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -           2172.2                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     4680      85      1599     318         2         2      16833          70223             2             1             44.0             22.0             20.0             21.0             229.0              1.0             23.0             23.0              48.0              0.0      24085.0      11895.0        82838.0       54934.0       49602.0       19418.0      39526.0       61435.0          0.0      48310.0       9220.0          0.0           1.0          0.0          0.0          0.0              1              0              0              0               2               1     12007.0     19433.0         23.0         20.0         183.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         236.0             225.0              47.0               0               0                 0               0               0                 0                 2                43                 0                22                  0                  0                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean  Active Std  Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   84.0  22123.0  454.0        -     12.0         -             -       8190.0            -               -       1294924.7               -           763.8                -               -            82.3               -                -               -           -           -             -            -            -            -           -            -           -           -  64835557.0   1807233.0            -  54086366.5           -           -           3.0             -           1.0             -       106391.0              -          -          -           -      1255.4            -      3384.8     26267.7            -          1.0            -            -            -            -              -            -             -            -           2167.3                -              -            1.0                -              -              -                -                -                -          10558.0                -              -1.0                 -             106.0                -  26017707.8  12295827.5  23787130.0          -         -        -        -        -   1.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std    Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0    12758      96     49212     429       443         6       8828        2999051            12            17            987.0           6816.0            517.0              0.0             82.25       152.450958           1412.0              0.0        400.941162        561.02832  2601.822998     9.669725  107108.960938  466868.34375     2474471.0           0.0    2988401.0   271672.8125  735130.0625    2474615.0         12.0    2801341.0   175083.8125    666028.75    2671870.0          0.0              0              0              0              0             252             364    4.001266     5.66846          0.0       1412.0    260.100006   457.735596  209521.890625             0             1             0             0             0             0               0             0            1.0     269.06897             82.25        400.941162               0               0                 0               0               0                 0                12               987                17              6816                 -1                265                  6                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   25.0        -      -        -        -         -             -       1630.0            -               -               -               -           124.1                -               -               -           580.7           2435.9               -           -           -             -            -            -  -30404480.0           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -   698101.0          -           -           -       3934.5           -           -            -          0.0          1.0            -            -            -            1.0            -             -            -                -           3824.9              -              -                -            1.0              -              1.0                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3486      85       134     318         2         2      14023          71537             2             1             51.0             26.0             24.0             25.0             245.0              1.0             27.0             27.0              53.0              0.0      30686.0      10681.0        84052.0       58328.0       52204.0       18928.0      41355.0       63210.0          0.0      50568.0      10998.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               2               1     10792.0     18119.0         27.0         24.0         200.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         274.0             240.0              51.0               0               0                 0               0               0                 0                 2                50                 0                26                  0                  0                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -       8120.0            -               -               -          1402.4               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -  34225291.7           -           -           -            -           -           -           -           1.0             -             -             -              -              -          -          -       658.0      1235.0            -      4056.5           -            -            -            -            -            -            -              -          1.0             -       5187.8                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3513      85       171     318         2         2       6039          12264             0             2              0.0             40.0              1.0              1.0               1.0              1.0             35.0              8.0              49.0              9.0      69171.0      76323.0        19117.0           0.0       34161.0       15823.0          1.0           1.0          0.0          0.0          0.0      12059.0       19470.0          0.0      12234.0      12314.0              0              0              0              0               0               2         0.0     77024.0          8.0         33.0         150.0        304.0        316.0             0             0             0             0             0             0               0             0            0.0         239.0               0.0              48.0               0               0                 0               0               0                 0                 0                 0                 1                40                  0                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean  Active Std Active Max  Active Min Idle Mean    Idle Std Idle Max Idle Min Label
0       -      -        -   11.0        -        -    1028.0             -       8010.0            -               -               -               -               -                -          4095.4               -               -                -          4312.2           -           -             -   23196808.6            -            -           -            -  18849633.5           -           -           -            -  37741568.8           -           -             -             -             -             -              -       289652.0          -          -           -           -            -           -           -            -            -            -            -          2.0            -              -            -             -            -                -                -              -              -                -              -              -              1.0                -                -          20595.0                -              -1.0                 -                 -                -           -  12382081.4          -  23501113.8         -  37277763.3        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2132      85        17     317         7         1       6378          62247             1             1              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0       6601.0        90589.0           0.0       61809.0       26414.0          1.0           1.0          0.0          0.0          0.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               3               3      4316.0     27403.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 0                 0                  0                 37                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max  Active Min Idle Mean    Idle Std Idle Max Idle Min Label
0       -   25.0        -  179.0        -        -    1954.0             -            -      21919.0               -      11405643.7               -          1333.4                -               -               -          1373.7                -               -           -           -             -            -            -            -           -            -  53284803.2  12585193.9           -           -   23313113.8           -           -           -             -             -             -           3.0              -         3773.0   401842.3          -           -           -            -           -    524453.8            -            -            -            -            -            -              -            -           4.6       2064.7                -                -              -            1.0              1.0              -              -              1.0           3524.0                -           5590.0       18370485.0              -1.0                 -                 -                -           -  5201890.4  9094061.7  19643619.4         -  13908238.7        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2237     192         9     131       106         1        683             93             0             2              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0      94070.0          357.0           0.0       77145.0       32754.0          1.0           1.0          0.0          0.0          0.0         63.0       33233.0          0.0         66.0         93.0              0              0              0              0               0               6         0.0     91259.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 1                 0                  0                 37                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   78.0  34000.0      -        -        -         -             -            -            -         69471.3               -          1372.0           519.6                -               -           770.9               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -   822885.9          -           -           -            -           -           -            -            -            -            -            -            -              -            -           4.4            -                -                -              -              -                -              -              -                -                -                -          13230.0                -              -1.0                 -             789.0                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      625      28     57913     110        53        17       3115          12505             0             2              0.0             88.0              0.0              0.0               0.0              0.0             60.0             28.0              44.0        22.627417  7037.140625   159.935013   12505.107422           0.0  12505.107422  12505.107422          0.0           0.0          0.0          0.0          0.0  12505.107422  12505.107422          0.0  12505.107422  12505.107422              0              0              0              0               0              16         0.0  159.935013         28.0         60.0     38.666668    18.475208   341.333344             0             0             0             0             0             0               0             0            0.0          58.0               0.0              44.0               0               0                 0               0               0                 0                 0                 0                 2                88                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  224.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -            570.0                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1616      50     56170     195        53        17       3847          16151             0             2              0.0            207.0              0.0              0.0               0.0              0.0            172.0             35.0             103.5        96.873627  12816.543945   123.831345        16151.0           0.0       16151.0       16151.0          0.0           0.0          0.0          0.0          0.0      16151.0       16151.0          0.0      16151.0      16151.0              0              0              0              0               0              16         0.0  123.831345         35.0        172.0     80.666664    79.096985  6256.333496             0             0             0             0             0             0               0             0            0.0         121.0               0.0             103.5               0               0                 0               0               0                 0                 0                 0                 2               207                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  2815.0   80.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      580      85       203     116         7         1       5651          62008             1             1              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0       6840.0        90350.0           0.0       61567.0       26174.0          1.0           1.0          0.0          0.0          0.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               3               3      4555.0     27642.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 0                 0                  0                 36                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -     787.0             -            -      21595.0               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -           2.0           1.0           2.0              -              -          -          -           -           -            -           -           -            -            -            -          2.0            -            -              -            -             -            -            430.9           1667.5              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3546      85       215     318         7         1       6218          18359            10            16            342.0            518.0            133.0              1.0             723.0            943.0            229.0              0.0            1054.0           4809.0     105887.0      90522.0         1871.0        5008.0       67720.0       19346.0      59521.0        1417.0       3464.0       2905.0        171.0      15107.0       27833.0       2036.0      15000.0          3.0              0              0              0              0              41              76     79138.0     85126.0          0.0        215.0        1772.0       2794.0       3009.0             0             1             0             0             0             0               0             0            1.0        1454.0             646.0             889.0               0               0                 0               0               0                 0                10               341                15               517                  0                 42                  6                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std  Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0   369.0      -  30467.0  235.0        -      6.0     966.0             -            -            -               -               -               -               -                -           828.7               -            30.4                -           778.6           -           -             -            -            -            -           -   37032275.6           -  117236208.2           -           -            -  54571450.1           -           -             -             -             -             -              -              -          -          -           -           -        535.4           -           -            -          2.0            -            -            -            -              -            -           7.8            -           1665.8                -            1.0              -                -            1.0            1.0                -                -                -           9159.0                -              -1.0                 -             643.0                -           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3373      96     49628       0       443         6      16712          31141             3             4            211.0            147.0            211.0              0.0         70.333336       121.820908            147.0              0.0             36.75             73.5  11496.098633   224.784042    5190.166504   5383.924316       10351.0          86.0      20704.0       10352.0  14177.491211      20377.0        327.0      20841.0        6947.0  5644.057129      10351.0        432.0              0              0              0              0              60             104   96.336021  128.448029          0.0        211.0         44.75    84.607918       7158.5             0             1             0             0             0             0               0             0            1.0     51.142857         70.333336             36.75               0               0                 0               0               0                 0                 3               211                 4               147                 -1                  8                  1                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max  Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   68.0        -  141.0        -        -         -             -       6466.0            -               -               -           381.9               -                -               -          1184.3           628.1                -               -           -    551345.7             -            -            -            -           -            -           -           -           -           -            -           -           -           -           1.0             -             -             -              -              -   195529.0          -       531.6           -       4260.1           -           -            -            -          2.0            -            -            -              -            -             -            -                -           2071.9              -              -                -              -            1.0                -           4632.0          14481.0                -                -                 -           52374.0             324.0                -  22180897.5          -          -  19041829.6         -        -        -        -   1.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1489       0     59796       7        53        17       8996        7000200             2             1             74.0             37.0             37.0             37.0              37.0              0.0             37.0             37.0              37.0              0.0    15.856689     0.428559      3500100.0   706927.1875     3999973.0     3000227.0    3999973.0     3999973.0          0.0    3999973.0    3999973.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              16               8    0.285706    0.142853         37.0         37.0          37.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0     49.333332              37.0              37.0               0               0                 0               0               0                 0                 2                74                 1                37                 -1                 -1                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  217.0        -  422.0        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -          3444.3           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -          2.0            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -              1.0           -          -          -          -         -        -        -        -   1.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      477      27       443      86     49251         6       1012            180             0             2              0.0             73.0              0.0              0.0               0.0              0.0             73.0              0.0              36.5        51.618793  405555.5625  11111.111328          180.0           0.0         180.0         180.0          0.0           0.0          0.0          0.0          0.0        180.0         180.0          0.0        180.0        180.0              0              1              0              0               0              40         0.0  11111.111328          0.0         73.0     48.666668    42.146568  1776.333374             0             0             0             1             1             0               0             0            0.0          73.0               0.0              36.5               0               0                 0               0               0                 0                 0                 0                 2                73                 -1                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 1)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -   3507468.7           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

In [24]:
e3 = exp.generate_counterfactuals(X_test[1000:1021], total_CFs=1, desired_class= 2)
e3.visualize_as_dataframe(show_only_changes=True)

 90%|█████████ | 19/21 [02:23<00:13,  6.95s/it]

No Counterfactuals found for the given configuration, perhaps try with different parameters... ; total time taken: 00 min 04 sec

 95%|█████████▌| 20/21 [02:28<00:06,  6.29s/it]

No Counterfactuals found for the given configuration, perhaps try with different parameters... ; total time taken: 00 min 04 sec

100%|██████████| 21/21 [02:37<00:00,  7.51s/it]

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len   Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1181      74       443      86     49247         6       1700            103             1             2              0.0             85.0              0.0              0.0               0.0              0.0             85.0              0.0              42.5        60.104076  825242.6875  29126.212891           51.5     48.790367          86.0          17.0          0.0           0.0          0.0          0.0          0.0         86.0          86.0          0.0         86.0         86.0              0              1              0              0              20              40  9708.738281  19417.476562          0.0         85.0          42.5    49.074772  2408.333252             0             0             0             1             1             0               0             0            2.0     56.666668               0.0              42.5               0               0                 0               0               0                 0                 1                 0                 2                85                 -1                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max    Idle Min Label
0       -      -  15141.0    3.0        -        -    8605.0             -            -            -               -      18205277.0               -               -                -               -           962.0               -                -               -           -           -    17636347.8            -            -            -           -   26063135.9           -           -           -  46448627.4   74862094.6           -           -           -             -             -           1.0             -              -              -          -          -       638.8       209.0            -           -           -            -          2.0            -            -            -            -              -            -             -       2377.7                -                -              -              -              1.0              -              -                -                -                -                -                -                 -           53142.0                 -                -           -          -          -          -         -        -        -  72945298.3   2.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0       43       0     59140       3      5355        17      15962         100304             3             1             72.0             24.0             24.0             24.0              24.0              0.0             24.0             24.0              24.0              0.0   957.090454    39.878769   33434.667969  57909.675781      100303.0           0.0     100303.0       50151.5  70924.929688     100303.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8   29.909077    9.969692         24.0         24.0          24.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          30.0              24.0              24.0               0               0                 0               0               0                 0                 3                72                 1                24                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std  Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -  532305200.4           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      336      85       198      95         7         1       6038          61414             1             1              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0       7434.0        89756.0           0.0       60972.0       25580.0          1.0           1.0          0.0          0.0          0.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               3               3      5149.0     28236.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 0                 0                  0                 32                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean    Idle Std   Idle Max Idle Min Label
0       -      -        -    6.0        -        -         -             -            -      16962.0               -      10592905.0               -               -           1078.4               -               -               -           1710.5               -           -           -             -    5881807.1            -            -           -            -           -           -           -  12759621.3            -           -  78430386.1           -             -           1.0             -             -              -              -          -          -           -        94.1            -      4542.3           -          2.0            -          1.0            -          2.0          1.0              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -        4453963.0              -1.0                 -                 -                -           -          -          -          -         -  25437604.1  4976934.9        -   2.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std   Flow IAT Max  Flow IAT Min    Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std    Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      933      50     54705     115      5355        17       8484         103892             3             1        72.231522        24.077175        24.077175        24.077175         24.077175              0.0        24.077175        24.077175         24.077175              0.0   927.014282    38.501503   34630.695312  59980.328125  103890.007812           1.0  103891.085938  51945.542969  73460.570312  103890.007812     1.077175          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8   28.876129    9.625376    24.077175    24.077175     24.077175          0.0          0.0             0             0             0             0             0             0               0             0            0.0     30.096468         24.077175         24.077175               0               0                 0               0               0                 0                 3                72                 1                24                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max  Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -    0.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -  22179272.9         -        -        -        -   2.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     4333      85      1194     318         2         2      37088           2699             0             2              0.0             61.0              1.0              1.0               1.0              1.0             59.0              8.0              86.0             43.0      94411.0      90461.0         6524.0           0.0       71957.0       31073.0          1.0           1.0          0.0          0.0          0.0       2502.0       29863.0          0.0       2462.0       2670.0              0              0              0              0               0               2         0.0     88231.0          8.0         58.0         233.0        569.0        653.0             0             0             0             0             0             0               0             0            0.0         354.0               0.0              83.0               0               0                 0               0               0                 0                 0                 0                 1                61                  0                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std  Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean  Active Std  Active Max  Active Min Idle Mean Idle Std    Idle Max     Idle Min Label
0       -    1.0        -      -        -        -         -             -            -      14624.0         12751.3               -          1322.2               -                -               -          1092.8               -            189.7          4839.6           -           -             -   45575825.4            -            -  25846797.1            -  62633674.9           -           -           -            -           -  110032315.9           -           3.0             -           1.0             -              -       339028.0          -          -           -           -        144.3       180.9           -            -          2.0            -            -            -            -              -            -           4.1            -                -                -              -              -                -              -              -              1.0           2898.0                -                -                -              -1.0                 -                 -                -           -  15612265.1  34322562.3  26857368.3         -        -  48482625.0  102702594.8   2.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean    Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0       96       0     51692       4      3702        17      18743         164969             3             1           1872.0            624.0            624.0            624.0             624.0              0.0            624.0            624.0             624.0              0.0  15130.115234    24.246981   54989.667969   95237.96875      164961.0           3.0     164964.0       82482.0  116642.921875     164961.0          3.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8   18.185234    6.061745        624.0        624.0         624.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         780.0             624.0             624.0               0               0                 0               0               0                 0                 3              1872                 1               624                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -         98019.9               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      278       0     50770       6        53        17      13343        7967755             3             1        92.625603        30.875202        30.875202        30.875202         30.875202              0.0        30.875202        30.875202         30.875202              0.0    15.500028     0.502023      2655918.5   1150520.875     3984397.5   1984189.125    5968586.5    2984293.25  1414360.875    3984397.5  1984189.125          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.376518    0.125506    30.875202    30.875202     30.875202          0.0          0.0             0             0             0             0             0             0               0             0            0.0     38.594002         30.875202         30.875202               0               0                 0               0               0                 0                 3                92                 1                30                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -           2.0             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0    13130      96     56747     430        53        17       5762          18894             0             2              0.0            207.0              0.0              0.0               0.0              0.0            172.0             35.0             103.5        96.873627  10955.859375   105.853714        18894.0           0.0       18894.0       18894.0          0.0           0.0          0.0          0.0          0.0      18894.0       18894.0          0.0      18894.0      18894.0              0              0              0              0               0              16         0.0  105.853714         35.0        172.0     80.666664    79.096985  6256.333496             0             0             0             0             0             0               0             0            0.0         121.0               0.0             103.5               0               0                 0               0               0                 0                 0                 0                 2               207                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std    Idle Max Idle Min Label
0       -    1.0        -      -  10787.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -  36953310.7           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -              1.0           -          -          -          -         -        -  42875739.1        -   2.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2971      85      1129     317         2         2      11701          82229             3             1             43.0              7.0              5.0              6.0             116.0              1.0              8.0              8.0              23.0              0.0       7740.0      17296.0        76695.0       69608.0       51642.0       12399.0      53827.0       56282.0      52156.0      50009.0       4659.0          0.0           1.0          0.0          0.0          0.0              1              0              0              0               4               1     18063.0      7324.0          8.0          5.0          47.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          50.0             114.0              22.0               0               0                 0               0               0                 0                 3                42                 0                 7                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -  61362.0    4.0        -        -         -             -            -            -          6285.7               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -   49358522.1           -           -           -             -             -             -             -       122159.0              -          -          -           -           -            -           -           -            -            -            -            -          1.0            -              -            -             -            -                -                -              -            1.0                -              -              -                -                -                -          19989.0                -              -1.0                 -                 -                -   1833964.5          -          -          -         -        -        -        -   2.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1369      50     49168     194       443         6      10578        4812483             1             1              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0     0.415586      4812483.0           0.0     4812483.0     4812483.0          0.0           0.0          0.0          0.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              20              20    0.207793    0.207793          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 1                 0                 -1                259                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min  Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -    1.0        -      -        -        -         -             -            -            -               -               -               -               -           1511.5               -               -          1424.4                -               -           -           -             -    7227260.9            -            -  -26692074.3   95777574.4           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -           7.1            -                -                -              -              -                -              -              -              1.0                -                -                -                -                 -                 -                 -              1.0           -          -          -          -         -        -        -        -   2.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      812       0     61956       6        53        17       3636        7953108             3             1       100.248245         33.41608         33.41608         33.41608          33.41608              0.0         33.41608         33.41608          33.41608              0.0    16.806549     0.502948     2651036.25    1141774.25    3969414.75   1984305.625    5953720.5    2976860.25  1403684.125   3969414.75  1984305.625          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.377211    0.125737     33.41608     33.41608      33.41608          0.0          0.0             0             0             0             0             0             0               0             0            0.0     41.770103          33.41608          33.41608               0               0                 0               0               0                 0                 3               100                 1                33                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -       146.6            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std   Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1186      58     50004     123      1900        17       3752        3045342             7             1           1225.0            175.0            175.0            175.0             175.0              0.0            175.0            175.0             175.0              0.0   459.718414     2.626962    435048.9375   542594.6875  1.015819e+06      2.624861    3045339.0      507556.5  555993.8125  1.015819e+06     2.624861          0.0           0.0          0.0          0.0          0.0              0              0              0              0              56               8    2.298592     0.32837        175.0        175.0         175.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0       196.875             175.0             175.0               0               0                 0               0               0                 0                 7              1225                 1               175                 -1                 -1                  7                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -    1.0        -      -        -        -         -             -        455.0            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   2.0

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      712      28     61909     110        53        17        199          15169             0             2              0.0            132.0              0.0              0.0               0.0              0.0            104.0             28.0              66.0        53.740116  8701.876953   131.846619   15169.194336           0.0  15169.194336  15169.194336          0.0           0.0          0.0          0.0          0.0  15169.194336  15169.194336          0.0  15169.194336  15169.194336              0              0              0              0               0              16         0.0  131.846619         28.0        104.0     53.333332     43.87862  1925.333374             0             0             0             0             0             0               0             0            0.0          80.0               0.0              66.0               0               0                 0               0               0                 0                 0                 0                 2               132                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  4526.0      -        -    2.0        -        -   38967.0             -            -            -               -       7794926.6               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -    121637.3            -            -            -            -          1.0            -              -            -             -       2607.2                -                -            1.0              -                -              -              -                -                -                -                -                -                 -                 -                 -              1.0           -          -          -          -         -        -        -        -   2.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot   Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1684      58     61620     174       443        17       2791        2445098            14            17      2041.689575      9360.239258           1250.0             33.0        152.160538        328.97168           1250.0             22.0        544.154907         538.6745  4663.194336    12.947882        83694.0   413218.0625    2251969.75      2.178229   2414930.75  199365.984375  640442.1875   2262366.25         10.0   2445098.25   153095.5625  563294.4375   2270523.75     2.178229              0              0              0              0             112             140    5.776452     7.17143         22.0       1250.0    399.253326   508.136017  259062.4375             0             0             0             0             0             0               0             0            1.0    412.881439        152.160538        544.154907               0               0                 0               0               0                 0                14              2041                17              9360                 -1                 -1                 14                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  2459.0    0.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -  116455005.1           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -   284312.2           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   2.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2878      85      1026     317         2         2      21106          76354             3             1             43.0              7.0              5.0              6.0             116.0              1.0              8.0              8.0              23.0              0.0       9887.0      22988.0        71309.0       62760.0       47551.0       12068.0      51106.0       53747.0      48448.0      46296.0       4786.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     23444.0     13199.0          8.0          5.0          47.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          50.0             114.0              22.0               0               0                 0               0               0                 0                 3                42                 0                 7                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min  Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std  Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -    0.0        -      -        -        -         -             -       6829.0       8887.0               -      18063361.6           903.1               -           2472.3               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -  -25306023.6            -           -           -           -             -             -             -           3.0              -              -          -          -           -           -            -      7708.0    554596.4            -            -          2.0            -            -            -              -          1.0             -            -                -                -              -              -                -              -              -                -                -                -          20070.0       32148597.0              -1.0                 -                 -                -           -  9434552.8  18150800.5          -         -        -        -        -   2.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1543      58     64069     173        53        17       4938          10267             0             2              0.0             88.0              0.0              0.0               0.0              0.0             60.0             28.0              44.0        22.627417  8570.818359   194.791321   10267.675781           0.0  10267.675781  10267.675781          0.0           0.0          0.0          0.0          0.0  10267.675781  10267.675781          0.0  10267.675781  10267.675781              0              0              0              0               0              16         0.0  194.791321         28.0         60.0     38.666668    18.475208   341.333344             0             0             0             0             0             0               0             0            0.0          58.0               0.0              44.0               0               0                 0               0               0                 0                 0                 0                 2                88                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -    5.0        -        -   19674.0             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -  78278589.5           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -      5583.5    139338.7            -            -            -            -            -            -              -            -             -            -           2592.8                -              -              -                -              -            1.0                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   2.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1565     118       443      86     49214         6        991            107             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0  18691.587891          107.0           0.0         107.0         107.0          0.0           0.0          0.0          0.0          0.0        107.0         107.0          0.0        107.0        107.0              0              0              0              0               0              40         0.0  18691.587891          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                257                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std  Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean  Active Std Active Max Active Min Idle Mean Idle Std Idle Max    Idle Min Label
0       -    8.0        -    0.0        -        -   15307.0             -            -            -               -               -               -           344.4                -          1358.8               -               -                -          4684.3  258073803.8           -             -            -            -            -           -   12875302.5           -  13519422.2           -           -            -           -           -           -             -             -             -           1.0              -       118357.0   389245.9          -       761.5           -            -           -      7678.1            -            -            -            -            -            -            1.0          1.0           8.8            -            459.3                -              -              -                -              -            1.0                -                -          92626.0                -                -                 -                 -                 -                -           -  15737218.7          -          -         -        -        -  69122442.4   2.0

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      666      54       443      52     49213         6        769             76             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0  26242.496094      76.214455           0.0     76.214455     76.214455          0.0           0.0          0.0          0.0          0.0    76.214455     76.214455          0.0    76.214455    76.214455              0              0              0              0               0              40         0.0  26242.496094          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                257                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean    Idle Std Idle Max Idle Min Label
0       -      -        -    2.0        -      8.0    5868.0    33752253.0            -            -        112540.6               -               -               -                -               -               -               -                -               -           -           -             -            -            -  -73689213.4  49297467.1            -  55262133.3           -           -  53838250.8            -           -           -           -             -             -             -           3.0       213183.0              -          -          -       775.1           -            -           -    615117.9          2.0            -            -            -            -            -              -            -             -            -                -            475.1              -              -                -              -              -                -                -         148172.0                -                -                 -                 -             996.0                -           -          -          -          -         -  10312962.7        -        -   2.0

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min   Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std   Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std   Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      600      28     49212     110       443         6        835          94400             3             3            517.0              0.0            517.0              0.0        172.333328       298.490082              0.0              0.0               0.0              0.0  5476.956055    63.562355   18880.013672  28356.800781  68388.710938     90.120041  81296.171875  40648.085938  56664.683594  80716.070312   580.104797  26011.365234  13005.682617   152.632935  13113.610352  12897.754883              0              0              0              0              60              84   31.781178   31.781178          0.0        517.0      73.85714   195.407639  38184.144531             0             1             0             0             0             0               0             0            1.0     86.166664        172.333328               0.0               0               0                 0               0               0                 0                 3               517                 3                 0                 -1                261                  1                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

No counterfactuals found!
Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0    12923      96     62913     429        53        17      17583          10815             0             2              0.0             88.0              0.0              0.0               0.0              0.0             60.0             28.0              44.0        22.627417  8136.847168   184.928345        10815.0           0.0       10815.0       10815.0          0.0           0.0          0.0          0.0          0.0      10815.0       10815.0          0.0      10815.0      10815.0              0              0              0              0               0              16         0.0  184.928345         28.0         60.0     38.666668    18.475208   341.333344             0             0             0             0             0             0               0             0            0.0          58.0               0.0              44.0               0               0                 0               0               0                 0                 0                 0                 2                88                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

No counterfactuals found!
Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2412      85       462     317         2         2      27038          77967             3             1             59.0             13.0             11.0             12.0             160.0              1.0             14.0             14.0              33.0              0.0      21691.0      21255.0        72919.0       80426.0       52559.0        7293.0      53974.0       56429.0      53816.0      50921.0       3894.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     21839.0     11586.0         14.0         11.0          97.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         106.0             158.0              32.0               0               0                 0               0               0                 0                 3                58                 0                13                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 2)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -    1.0        -  356.0        -        -         -             -       5107.0            -               -      25754476.0               -               -                -               -           151.6               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -  77880566.2             -           1.0             -           1.0              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -           1782.1                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   2.0

In [25]:
e4 = exp.generate_counterfactuals(X_test[1500:1521], total_CFs=1, desired_class= 3)
e4.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 21/21 [02:34<00:00,  7.37s/it]

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      502      28     49188      89        80         6       3202        4797238             1             1              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0     0.416907      4797238.0           0.0     4797238.0     4797238.0          0.0           0.0          0.0          0.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              20              20    0.208453    0.208453          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 1                 0                 -1              65049                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  4501.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1560      50     50165     195        53        17       7106          12425             0             2              0.0            159.0              0.0              0.0               0.0              0.0            116.0             43.0              79.5        51.618793  12796.780273    160.96579        12425.0           0.0       12425.0       12425.0          0.0           0.0          0.0          0.0          0.0      12425.0       12425.0          0.0      12425.0      12425.0              0              0              0              0               0              16         0.0   160.96579         43.0        116.0     67.333336    42.146568  1776.333374             0             0             0             0             0             0               0             0            0.0         101.0               0.0              79.5               0               0                 0               0               0                 0                 0                 0                 2               159                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -           4176.0                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min   Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std   Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1166      58     61373     118      5355        17       4105          93458             3             1             72.0             24.0             24.0             24.0              24.0              0.0             24.0             24.0              24.0              0.0  1027.196411     42.79985   31152.976562  53956.808594  93456.929688           1.0  93457.929688  46728.964844  66083.320312  93456.929688          1.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8   32.099888   10.699963         24.0         24.0          24.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          30.0              24.0              24.0               0               0                 0               0               0                 0                 3                72                 1                24                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   54.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3545      85       214     318         7         1       8081          23236            11            18            342.0            518.0            133.0              1.0             605.0            901.0            229.0              0.0             701.0           3789.0     105669.0      90810.0         1768.0        4719.0       67982.0           2.0      60880.0        1263.0       3185.0       2985.0        110.0      15446.0       27295.0       1761.0      15289.0          1.0              0              0              0              0              46              85     79184.0     85204.0          0.0        215.0        1401.0       2057.0       2257.0             0             1             0             0             0             0               0             0            1.0        1176.0             550.0             586.0               0               0                 0               0               0                 0                11               341                17               517                  0                 42                  6                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -      11533.0               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -       16400254.0              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      785      28     63503     111        53        17        881          12137             0             2              0.0            132.0              0.0              0.0               0.0              0.0            104.0             28.0              66.0        53.740116  10875.488281   164.780136   12137.921875           0.0  12137.921875  12137.921875          0.0           0.0          0.0          0.0          0.0  12137.921875  12137.921875          0.0  12137.921875  12137.921875              0              0              0              0               0              16         0.0  164.780136         28.0        104.0     53.333332     43.87862  1925.333374             0             0             0             0             0             0               0             0            0.0          80.0               0.0              66.0               0               0                 0               0               0                 0                 0                 0                 2               132                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean    Idle Std Idle Max Idle Min Label
0       -   50.0        -      -        -        -   23092.0             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -  65353629.8           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -  19384939.7        -        -   3.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3869       0       443     184     50356         6      16737            114             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0  17543.859375          114.0           0.0         114.0         114.0          0.0           0.0          0.0          0.0          0.0        114.0         114.0          0.0        114.0        114.0              0              0              0              0               0              40         0.0  17543.859375          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                260                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -   82.0        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1618      50     56747     195        53        17       9250          15430             0             2              0.0            207.0              0.0              0.0               0.0              0.0            172.0             35.0             103.5        96.873627  13415.424805    129.61763        15430.0           0.0       15430.0       15430.0          0.0           0.0          0.0          0.0          0.0      15430.0       15430.0          0.0      15430.0      15430.0              0              0              0              0               0              16         0.0   129.61763         35.0        172.0     80.666664    79.096985  6256.333496             0             0             0             0             0             0               0             0            0.0         121.0               0.0             103.5               0               0                 0               0               0                 0                 0                 0                 2               207                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -          19958.0                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1485      50     61597     194        53        17       4578          12987             0             2              0.0             88.0              0.0              0.0               0.0              0.0             60.0             28.0              44.0        22.627417  6776.006836   154.000153        12987.0           0.0       12987.0       12987.0          0.0           0.0          0.0          0.0          0.0      12987.0       12987.0          0.0      12987.0      12987.0              0              0              0              0               0              16         0.0  154.000153         28.0         60.0     38.666668    18.475208   341.333344             0             0             0             0             0             0               0             0            0.0          58.0               0.0              44.0               0               0                 0               0               0                 0                 0                 0                 2                88                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -       368.9            -           -           -            -            -            -            -            -            -            1.0            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2432      85       485     317         2         2      31983          50929             2             1             44.0             22.0             20.0             21.0             229.0              1.0             23.0             23.0              48.0              0.0      35357.0      27572.0        67121.0       58921.0       28236.0       33382.0      16039.0       51302.0          0.0      34066.0       4721.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               2               1     27757.0     37483.0         23.0         20.0         183.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         236.0             225.0              47.0               0               0                 0               0               0                 0                 2                43                 0                22                  0                  0                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean    Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0    10690      96     59807     264      3702        17       6788         170871             3             1           1968.0            656.0            656.0            656.0             656.0              0.0            656.0            656.0             656.0              0.0  15356.614258    23.409473        56957.0  98648.953125      170867.0           2.0     170869.0       85434.5  120819.796875     170867.0          2.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8   17.557104    5.852368        656.0        656.0         656.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         820.0             656.0             656.0               0               0                 0               0               0                 0                 3              1968                 1               656                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   51.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -  45738701.7           -            -           -           -           -           3.0             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min   Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1217      58     57320     123      3702        17       3184          73335             3             1           1968.0            656.0            656.0            656.0             656.0              0.0            656.0            656.0             656.0              0.0  35780.957031     54.54414   24445.101562  42325.472656   73318.34375      7.477638  73325.828125  36662.914062  51838.613281  73318.34375     7.477638          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8   40.908104   13.636035        656.0        656.0         656.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         820.0             656.0             656.0               0               0                 0               0               0                 0                 3              1968                 1               656                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   43.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -    383688.1            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2409      85       458     317         2         2       1296           7869             0             2              0.0             40.0              1.0              1.0               1.0              1.0             35.0              8.0              49.0              9.0      74039.0      81617.0        14093.0           0.0       19416.0        4242.0          1.0           1.0          0.0          0.0          0.0       7604.0       11858.0          0.0       7752.0       7857.0              0              0              0              0               0               2         0.0     82395.0          8.0         33.0         150.0        304.0        316.0             0             0             0             0             0             0               0             0            0.0         239.0               0.0              48.0               0               0                 0               0               0                 0                 0                 0                 1                40                  0                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -  46463.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -   32795300.4            -            -           -            -           -           -           -           -            -           -  81638290.8           -             -             -             -             -              -              -          -          -       575.0           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      738      45       443      86     49209         6       3143        3473903             5             2            365.0             73.0             73.0             73.0              73.0              0.0             73.0              0.0              36.5        51.618793    126.08297     2.015025    578983.8125    637056.875     1727881.0         791.0    3255985.0     813996.25  669088.0625    1727881.0     216036.0    3473903.0     3473903.0          0.0    3473903.0    3473903.0              0              1              0              0             100              40    1.439303    0.575721          0.0         73.0        63.875    25.809397      666.125             0             0             0             1             1             0               0             0            0.0          73.0              73.0              36.5               0               0                 0               0               0                 0                 5               365                 2                73                 -1                  0                  5                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -   85.0        -        -         -             -            -            -               -               -               -               -                -               -               -               -           4281.2               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -           1757.8                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     4319      85      1176     318         2         2       4828           6415             0             2              0.0             40.0              1.0              1.0               1.0              1.0             35.0              8.0              49.0              9.0      76749.0      84384.0        12419.0           0.0       15231.0        2757.0          1.0           1.0          0.0          0.0          0.0       6156.0        7812.0          0.0       6262.0       6402.0              0              0              0              0               0               2         0.0     84175.0          8.0         33.0         150.0        304.0        316.0             0             0             0             0             0             0               0             0            0.0         239.0               0.0              48.0               0               0                 0               0               0                 0                 0                 0                 1                40                  0                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min   Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -  27746.0        -         -             -            -            -        149199.7               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -       533.2           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -           6505.0                -                -                -              -1.0                 -                 -                -           -          -          -          -  71568826.9        -        -        -   3.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      490       0     55215       6        53        17       1560        7968598             3             1       123.447632        41.149212        41.149212        41.149212         41.149212              0.0        41.149212        41.149212         41.149212              0.0    20.655418      0.50197     2656199.75     1136536.5     3968559.0   1999750.125    5968849.0     2984424.5  1391776.375    3968559.0  2000289.875          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.376478    0.125493    41.149212    41.149212     41.149212          0.0          0.0             0             0             0             0             0             0               0             0            0.0     51.436512         41.149212         41.149212               0               0                 0               0               0                 0                 3               123                 1                41                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std   Idle Max    Idle Min Label
0       -  112.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -          2.0            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -  7730425.2  57770537.7   3.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1111       0     51733       7        53        17       4007        6984203             2             1             56.0             28.0             28.0             28.0              28.0              0.0             28.0             28.0              28.0              0.0    12.027142     0.429541      3492101.5      696004.5     3984251.0     2999952.0    3984251.0     3984251.0          0.0    3984251.0    3984251.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              16               8    0.286361     0.14318         28.0         28.0          28.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0     37.333332              28.0              28.0               0               0                 0               0               0                 0                 2                56                 1                28                 -1                 -1                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -   54.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -           3527.6              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1383      85       106     175        10         2       1041          59936             7             1           2310.0            212.0            183.0             74.0            3984.0              1.0            205.0             77.0            5116.0              0.0      56873.0      29669.0        64416.0       84522.0       57239.0           2.0      45893.0       48867.0      56765.0      55135.0          1.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0              10               1     30293.0     29729.0         62.0        189.0        7665.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0        6272.0            3291.0            4097.0               0               0                 0               0               0                 0                 7              2309                 0               211                  0                  0                  7                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std   Idle Max Idle Min Label
0       -      -  38292.0      -  20747.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -  86866374.2            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -    456740.8            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -              1.0           -          -          -          -         -        -  5421392.7        -   3.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2245      85       216     317         7         1      17393          37995            14            24            412.0            650.0            133.0              1.0             703.0            837.0            229.0              0.0             430.0            584.0      77547.0      62412.0        31188.0       29074.0        4904.0           2.0       8927.0       24248.0      24736.0      26236.0         17.0      29264.0       27176.0      15752.0      28016.0          1.0              0              0              0              0              60             107     55487.0     70133.0          0.0        215.0        1026.0       1062.0       1165.0             0             1             0             0             0             0               0             0            1.0         916.0             630.0             401.0               0               0                 0               0               0                 0                14               411                23               649                  0                 47                  8                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -  16650.0        -         -             -            -            -               -               -            48.6               -                -               -               -           448.7                -          5373.8           -           -             -            -            -  -17729083.8           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -          1.0            -            -            -            -            -              -            -             -            -                -                -              -              -                -            1.0              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3836      85       617     318         7         2       2276          37914            16            20            951.0           1681.0            195.0             11.0            2001.0           2304.0            215.0              2.0            2985.0           3608.0      85674.0      62559.0        25887.0       27452.0       68988.0       12763.0       7796.0       17533.0      22422.0      22029.0         27.0      29127.0       27170.0      15506.0      27747.0          2.0              0              0              0              0              24              34     58022.0     70161.0          2.0        200.0        4626.0       4717.0       4941.0             0             0             0             0             0             0               0             0            1.0        3889.0            1684.0            2473.0               0               0                 0               0               0                 0                16               950                19              1680                  0                  0                 16                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -  29741868.5            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1722     116         0     172         0         0       2513        5628846            28             1              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0      5.15205   201030.21875   553665.4375    2536622.75      0.251915    5628838.0  208475.46875  562782.1875   2536622.75     0.251915          0.0           0.0          0.0          0.0          0.0              0              0              0              0               0               0    4.974394    0.177657          0.0          0.0           0.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                28                 0                 1                 0                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -   13873.0             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min    Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std   Fwd IAT Max  Fwd IAT Min    Bwd IAT Tot  Bwd IAT Mean   Bwd IAT Std   Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std    Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      259      28     49238      53       443         6       1614         208037            11            18      1219.217651      6587.361328            517.0              0.0        101.663727       160.201965           1412.0              0.0        353.595276       555.982117  37580.226562   147.030014    7036.722168  17145.322266  78122.265625      1.654134  179358.484375  16602.085938  33017.84375  92394.945312    22.105307  208037.421875  11780.450195  21193.912109  78122.265625     1.654134              0              0              0              0             247             397   57.318531   89.711479          0.0       1412.0    247.841766   452.624695  204927.640625             0             1             0             0             0             0               0             0            1.0    256.002228        101.663727        353.595276               0               0                 0               0               0                 0                11              1219                18              6587                 -1                267                  7                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 3)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -  53634.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   3.0

In [26]:
e5 = exp.generate_counterfactuals(X_test[2000:2021], total_CFs=1, desired_class= 4)
e5.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 21/21 [03:28<00:00,  9.94s/it]

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      803      52         0      95         0         0       1509        5705440            22             1              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0     4.031241    259338.1875   616444.4375     2543878.5           1.0    5705437.0  271687.46875  628872.8125    2543878.5          1.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0               0               0     3.85597    0.175271          0.0          0.0           0.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                22                 0                 1                 0                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  8653.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1508     115       443      85     49196         6       1290            176             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0  11363.636719          176.0           0.0         176.0         176.0          0.0           0.0          0.0          0.0          0.0        176.0         176.0          0.0        176.0        176.0              0              0              0              0               0              40         0.0  11363.636719          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                254                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  6985.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean   Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std    Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1528      50     49216     195       443         6       2742        3003101            17            20           1175.0           7414.0            517.0              0.0         69.117645       134.853104           1412.0              0.0        370.700012       526.911377  2860.043701    12.320598    83419.46875     442100.25     2654317.0           2.0    2988423.0   186776.4375   660282.375    2654317.0          4.0     147914.0   7784.947266  15992.423828      68538.0          2.0              0              0              0              0             364             424    5.660815    6.659783          0.0       1412.0    226.026321   417.660309  174440.140625             0             1             0             0             0             0               0             0            1.0    232.135132         69.117645        370.700012               0               0                 0               0               0                 0                17              1175                20              7414                 -1                269                  7                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  209.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1213      85       774     161        12         2       6057          15400             3             1             34.0              5.0              3.0              4.0             108.0              1.0              6.0              4.0              19.0              0.0      54335.0      72505.0        21231.0       10404.0       74460.0           2.0      59813.0        7019.0       6214.0       4996.0          1.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     73170.0     68529.0          4.0          3.0          39.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          39.0             106.0              18.0               0               0                 0               0               0                 0                 3                33                 0                 5                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean  Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  9166.0      -  60991.0      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -  13247641.8          -          -         -        -        -        -   4.0

Query instance (original outcome : 3)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1463      50     57913     194        53        17       2574          12854             0             2              0.0             88.0              0.0              0.0               0.0              0.0             60.0             28.0              44.0        22.627417  6846.118164   155.593582        12854.0           0.0       12854.0       12854.0          0.0           0.0          0.0          0.0          0.0      12854.0       12854.0          0.0      12854.0      12854.0              0              0              0              0               0              16         0.0  155.593582         28.0         60.0     38.666668    18.475208   341.333344             0             0             0             0             0             0               0             0            0.0          58.0               0.0              44.0               0               0                 0               0               0                 0                 0                 0                 2                88                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      3

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  162.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s   Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     5798       0       443     184     53282         6      16836            139             0             2              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0  14388.489258          139.0           0.0         139.0         139.0          0.0           0.0          0.0          0.0          0.0        139.0         139.0          0.0        139.0        139.0              0              0              0              0               0              40         0.0  14388.489258          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 2                 0                 -1                260                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -   59828159.3           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -  2888699.4          -          -         -        -        -        -     -

Query instance (original outcome : 5)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min   Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      706      28     51411     111        53        17       2776          15686             0             2              0.0            194.0              0.0              0.0               0.0              0.0            156.0             38.0              97.0        83.438599  12367.880859   127.503929   15686.649414           0.0  15686.649414  15686.649414          0.0           0.0          0.0          0.0          0.0  15686.649414  15686.649414          0.0  15686.649414  15686.649414              0              0              0              0               0              16         0.0  127.503929         38.0        156.0     77.333336    68.127335  4641.333496             0             0             0             0             0             0               0             0            0.0         116.0               0.0              97.0               0               0                 0               0               0                 0                 0                 0                 2               194                 -1                 -1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      5

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  5704.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     3460     193         9     131        41         1      23249            127             0             2              0.0             34.0              1.0              1.0               1.0              1.0             41.0              0.0              37.0             41.0     107057.0      93980.0          459.0           0.0       11641.0        2016.0          1.0           1.0          0.0          0.0          0.0         97.0        5728.0          0.0        100.0        127.0              0              1              0              0               0               6         0.0     91196.0          0.0         40.0         207.0        566.0        650.0             0             0             0             1             1             0               0             0            0.0         336.0               0.0              36.0               0               0                 0               0               0                 0                 0                 0                 1                34                  0                  1                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2234     192         9     131       103         1       3340            123             0             2              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0      93992.0          453.0           0.0       11362.0        1955.0          1.0           1.0          0.0          0.0          0.0         93.0        5072.0          0.0         96.0        123.0              0              0              0              0               0               6         0.0     91204.0          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            0.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 0                 0                 1                 0                  0                 33                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -          94190.0                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      585       0     56960       6        53        17      16926        7999069             3             1             84.0             28.0             28.0             28.0              28.0              0.0             28.0             28.0              28.0              0.0     14.00163     0.500058     2666356.25     1154994.5     4000029.0     1999032.0    6000037.0     3000018.5  1414228.375    4000029.0    2000008.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8    0.375044    0.125015         28.0         28.0          28.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          35.0              28.0              28.0               0               0                 0               0               0                 0                 3                84                 1                28                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  179.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 4)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std   Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean   Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     5517      96     52871       0       443         6      16822          35210             3             4            211.0            147.0            211.0              0.0         70.333336       121.820908            147.0              0.0             36.75             73.5  10167.566406   198.807159    5868.333496    5918.69043       12089.0         204.0      22917.0       11458.5  15572.612305      22470.0        447.0      25693.0   8564.333008  6594.048828      12647.0        957.0              0              0              0              0              60             104   85.203064  113.604088          0.0        211.0         44.75    84.607918       7158.5             0             1             0             0             0             0               0             0            1.0     51.142857         70.333336             36.75               0               0                 0               0               0                 0                 3               211                 4               147                 -1                  8                  1                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      4

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max  Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -  -43094636.2           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -          1.0            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -     -

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1431      58     49170     173       443         6       4528        4792469             1             1              0.0              0.0              0.0              0.0               0.0              0.0              0.0              0.0               0.0              0.0          0.0     0.417321      4792469.0           0.0     4792469.0     4792469.0          0.0           0.0          0.0          0.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              20              20    0.208661    0.208661          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 1                 0                 -1                259                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -  440.0        -        -   26747.0             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 1)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max   Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      746      45       443      86     49226         6       2238        3961929             5             2            365.0             73.0             73.0             73.0              73.0              0.0             73.0              0.0              36.5        51.618793    110.55867     1.766919     660321.625      728176.0    1979255.75    439.411621    3712362.0      928090.5  765914.4375   1979255.75  247449.65625   3961929.75    3961929.75          0.0   3961929.75   3961929.75              0              1              0              0             100              40    1.262085    0.504834          0.0         73.0        63.875    25.809397      666.125             0             0             0             1             1             0               0             0            0.0          73.0              73.0              36.5               0               0                 0               0               0                 0                 5               365                 2                73                 -1                  0                  5                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      1

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -  305.0        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -            1.0            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1487       0     59755       7        53        17       8591        3985652             1             1             43.0             43.0             43.0             43.0              43.0              0.0             43.0             43.0              43.0              0.0    21.577398       0.5018      3985652.0           0.0     3985652.0     3985652.0          0.0           0.0          0.0          0.0          0.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0               8               8      0.2509      0.2509         43.0         43.0          43.0          0.0          0.0             0             0             0             0             0             0               0             0            1.0          64.5              43.0              43.0               0               0                 0               0               0                 0                 1                43                 1                43                 -1                 -1                  1                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  161.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0      921       0     64249       6        53        17      15526        7999577             3             1             84.0             28.0             28.0             28.0              28.0              0.0             28.0             28.0              28.0              0.0    14.000739     0.500026      2666526.0    1155136.75     4000363.0   1999202.125    6000375.5    3000187.75   1414461.25    4000363.0  2000012.625          0.0           0.0          0.0          0.0          0.0              0              0              0              0              24               8     0.37502    0.125007         28.0         28.0          28.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          35.0              28.0              28.0               0               0                 0               0               0                 0                 3                84                 1                28                 -1                 -1                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  216.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -      4426.7           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1492      85       693     175         9         2       2046          51395             3             1            198.0             62.0             47.0             40.0            1402.0              1.0             76.0             40.0             176.0              0.0      38298.0      28332.0        66265.0       86134.0       44374.0       24494.0      31294.0       50601.0      58419.0      45131.0         11.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     28473.0     37022.0         41.0         78.0         497.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0         524.0            1188.0             172.0               0               0                 0               0               0                 0                 3               197                 0                62                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

   Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  13120.0      -        -      -  56404.0        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -   9902762.4           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -           1793.5              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2700      85       817     317         2         2       4910           5014             0             2              0.0             40.0              1.0              1.0               1.0              1.0             35.0              8.0              49.0              9.0      81922.0      87258.0        10721.0           0.0        5930.0        1170.0          1.0           1.0          0.0          0.0          0.0       4795.0        1115.0          0.0       4786.0       5002.0              0              0              0              0               0               2         0.0     85875.0          8.0         33.0         150.0        304.0        316.0             0             0             0             0             0             0               0             0            0.0         239.0               0.0              48.0               0               0                 0               0               0                 0                 0                 0                 1                40                  0                  0                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

   Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0  13288.0      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -  62783391.2           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -              1.0                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1285      85      1620     161        12         2      34114          22575             3             1             34.0              5.0              3.0              4.0             108.0              1.0              6.0              4.0              19.0              0.0      46227.0      65003.0        28934.0       20236.0        6960.0           2.0       5317.0       14453.0      13640.0      12659.0          1.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     65775.0     60460.0          4.0          3.0          39.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          39.0             106.0              18.0               0               0                 0               0               0                 0                 3                33                 0                 5                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

   Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std    Idle Max Idle Min Label
0  13458.0      -        -      -        -     15.0         -             -            -            -               -               -               -               -                -               -               -               -                -          5191.5           -           -             -            -            -  -22062714.8           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -  9684726.6          -         -        -  10654982.0        -   4.0

Query instance (original outcome : 2)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     1550       0     61104       7        53        17      12356        6953041             2             1             68.0             34.0             34.0             34.0              34.0              0.0             34.0             34.0              34.0              0.0     14.66984     0.431466      3476520.5   695407.6875     3968248.0     2984793.0    3968248.0     3968248.0          0.0    3968248.0    3968248.0          0.0           0.0          0.0          0.0          0.0              0              0              0              0              16               8    0.287644    0.143822         34.0         34.0          34.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0     45.333332              34.0              34.0               0               0                 0               0               0                 0                 2                68                 1                34                 -1                 -1                  2                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      2

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -  168.0        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -                 -                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len  Fwd Pkts/s  Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2926      85      1081     317         2         2      20678          81775             3             1             43.0              7.0              5.0              6.0             116.0              1.0              8.0              8.0              23.0              0.0       8151.0      17747.0        76244.0       73259.0       51963.0       11689.0      54081.0       56532.0      52546.0      50330.0       4588.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               4               1     18514.0      7778.0          8.0          5.0          47.0          0.0          0.0             0             0             0             0             0             0               0             0            0.0          50.0             114.0              22.0               0               0                 0               0               0                 0                 3                42                 0                 7                  0                  0                  3                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -           -           -           -           -            -           -           -           -             -             -             -             -              -       115233.0          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   4.0

Query instance (original outcome : 0)

   Flow ID  Src IP  Src Port  Dst IP  Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  Flow Byts/s  Flow Pkts/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  Fwd Header Len  Bwd Header Len   Fwd Pkts/s    Bwd Pkts/s  Pkt Len Min  Pkt Len Max  Pkt Len Mean  Pkt Len Std  Pkt Len Var  FIN Flag Cnt  SYN Flag Cnt  RST Flag Cnt  PSH Flag Cnt  ACK Flag Cnt  URG Flag Cnt  CWE Flag Count  ECE Flag Cnt  Down/Up Ratio  Pkt Size Avg  Fwd Seg Size Avg  Bwd Seg Size Avg  Fwd Byts/b Avg  Fwd Pkts/b Avg  Fwd Blk Rate Avg  Bwd Byts/b Avg  Bwd Pkts/b Avg  Bwd Blk Rate Avg  Subflow Fwd Pkts  Subflow Fwd Byts  Subflow Bwd Pkts  Subflow Bwd Byts  Init Fwd Win Byts  Init Bwd Win Byts  Fwd Act Data Pkts  Fwd Seg Size Min  Active Mean  Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label
0     2028      85        22     278         4         1      35110          63849             1             1              0.0              0.0              1.0              1.0               1.0              1.0              0.0              0.0               0.0              0.0          1.0  4999.724609   92188.273438           0.0  63417.273438  28016.275391          1.0           1.0          0.0          0.0          0.0          0.0           1.0          0.0          0.0          0.0              0              0              0              0               3               3  2716.724609  25802.724609          0.0          0.0           0.0          0.0          0.0             1             0             0             0             1             0               0             0            1.0           0.0               0.0               0.0               0               0                 0               0               0                 0                 1                 0                 0                 0                  0                 37                  0                 0          0.0         0.0         0.0         0.0        0.0       0.0       0.0       0.0      0

Diverse Counterfactual set (new outcome: 4)

  Flow ID Src IP Src Port Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min Label
0       -      -        -      -        -        -         -             -            -            -               -               -               -               -                -               -               -               -                -               -           -           -             -            -            -            -           -            -   1852004.2           -           -           -            -           -           -           -             -           1.0             -             -              -              -          -          -           -           -            -           -           -            -            -            -            -            -            -              -            -             -            -                -                -              -              -                -              -              -                -                -                -                -                -              -1.0                 -                 -                -           -          -          -          -         -        -        -        -   4.0

In [1]:
e6 = exp.generate_counterfactuals(X_test[2500:2521], total_CFs=1, desired_class= 5)
e6.visualize_as_dataframe(show_only_changes=True)

NameError: name 'exp' is not defined